# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f52ec86ee6f29e941df4d75aeb74d44eed65cdf55c0e4b08362669b1ff2f55baee6173976a57a5c8c55dfb13074d79baf8e3a17b79642ace4e63db7ccdd77afd

test:
  secret_key_base: ae90f001ceb06cb6c38195f08e05f957a810703f165bfb84630f89fc7366b02987ddfd5a384e802a8ee891a14b59c5669cb0ed39668816178054a8bf210481e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= Settings.secret_token %>
