app:
  name: Course Cart

secret_token: # set in settings.local.yml

banner:
  connection_string: # set in settings.local.yml

cas:
  url: "https://login.biola.edu/cas"

accounts:
  create_url: "https://accounts.biola.edu/create"

touch_net:
  production: # when nil will use Rails.env

sentry:
  url: # Set this in settings.local.yml

urn_namespaces:
  - "urn:biola:apps:course-cart:"
  - "urn:biola:apps:all:"

email:
  smtp:
    server: postfix.biola.edu
  from: no-reply@biola.edu

exceptions:
  mail_to:
  - appdev@biola.edu
